vscode:
  extensions:
    - 'dbaeumer.vscode-eslint'
    - 'eamodio.gitlens'
    - 'shakram02.bash-beautify'
    - 'esbenp.prettier-vscode'
    - 'redjue.git-commit-plugin'
    - 'eamodio.gitlens'

tasks:
  - name: Start
    init: yarn && yarn codegen